// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	twitter "github.com/dghubble/go-twitter/twitter"
)

func AnyPtrToTwitterStatusShowParams() *twitter.StatusShowParams {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*twitter.StatusShowParams))(nil)).Elem()))
	var nullValue *twitter.StatusShowParams
	return nullValue
}

func EqPtrToTwitterStatusShowParams(value *twitter.StatusShowParams) *twitter.StatusShowParams {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *twitter.StatusShowParams
	return nullValue
}
