// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	twitter "github.com/dghubble/go-twitter/twitter"
)

func AnyPtrToTwitterTweet() *twitter.Tweet {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*twitter.Tweet))(nil)).Elem()))
	var nullValue *twitter.Tweet
	return nullValue
}

func EqPtrToTwitterTweet(value *twitter.Tweet) *twitter.Tweet {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *twitter.Tweet
	return nullValue
}
