// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	twitter "github.com/dghubble/go-twitter/twitter"
)

func AnyPtrToTwitterHomeTimelineParams() *twitter.HomeTimelineParams {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*twitter.HomeTimelineParams))(nil)).Elem()))
	var nullValue *twitter.HomeTimelineParams
	return nullValue
}

func EqPtrToTwitterHomeTimelineParams(value *twitter.HomeTimelineParams) *twitter.HomeTimelineParams {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *twitter.HomeTimelineParams
	return nullValue
}
