// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/petergtz/alexa-twitter/verbalizer (interfaces: TwitterTimelineClient)

package verbalizer_test

import (
	twitter "github.com/dghubble/go-twitter/twitter"
	pegomock "github.com/petergtz/pegomock"
	http "net/http"
	"reflect"
	"time"
)

type MockTwitterTimelineClient struct {
	fail func(message string, callerSkip ...int)
}

func NewMockTwitterTimelineClient(options ...pegomock.Option) *MockTwitterTimelineClient {
	mock := &MockTwitterTimelineClient{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockTwitterTimelineClient) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockTwitterTimelineClient) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockTwitterTimelineClient) HomeTimeline(_param0 *twitter.HomeTimelineParams) ([]twitter.Tweet, *http.Response, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockTwitterTimelineClient().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("HomeTimeline", params, []reflect.Type{reflect.TypeOf((*[]twitter.Tweet)(nil)).Elem(), reflect.TypeOf((**http.Response)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 []twitter.Tweet
	var ret1 *http.Response
	var ret2 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].([]twitter.Tweet)
		}
		if result[1] != nil {
			ret1 = result[1].(*http.Response)
		}
		if result[2] != nil {
			ret2 = result[2].(error)
		}
	}
	return ret0, ret1, ret2
}

func (mock *MockTwitterTimelineClient) VerifyWasCalledOnce() *VerifierMockTwitterTimelineClient {
	return &VerifierMockTwitterTimelineClient{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockTwitterTimelineClient) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierMockTwitterTimelineClient {
	return &VerifierMockTwitterTimelineClient{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockTwitterTimelineClient) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierMockTwitterTimelineClient {
	return &VerifierMockTwitterTimelineClient{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockTwitterTimelineClient) VerifyWasCalledEventually(invocationCountMatcher pegomock.Matcher, timeout time.Duration) *VerifierMockTwitterTimelineClient {
	return &VerifierMockTwitterTimelineClient{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockTwitterTimelineClient struct {
	mock                   *MockTwitterTimelineClient
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockTwitterTimelineClient) HomeTimeline(_param0 *twitter.HomeTimelineParams) *MockTwitterTimelineClient_HomeTimeline_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "HomeTimeline", params, verifier.timeout)
	return &MockTwitterTimelineClient_HomeTimeline_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockTwitterTimelineClient_HomeTimeline_OngoingVerification struct {
	mock              *MockTwitterTimelineClient
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockTwitterTimelineClient_HomeTimeline_OngoingVerification) GetCapturedArguments() *twitter.HomeTimelineParams {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockTwitterTimelineClient_HomeTimeline_OngoingVerification) GetAllCapturedArguments() (_param0 []*twitter.HomeTimelineParams) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]*twitter.HomeTimelineParams, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(*twitter.HomeTimelineParams)
		}
	}
	return
}
